app = "faq-slack-bot"
primary_region = "mad"

[build]
  image = "aaalexlit/faq-slack-bot:main"

[env]
  PINECONE_ENV = "gcp-starter"
  TEST_CHANNEL_ID = "C05DTQECY66"
  TEST_WS_CHANNEL_ID = "C05C3SGMLBB"
