name: Fly Rollback
on:
  workflow_dispatch:
jobs:
  rollback:
    name: Rollback to the previously deployed image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --image aaalexlit/faq-slack-bot:previous
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}