name: Fly Deploy
on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker image tag to be deployed. by default `aaalexlit/faq-slack-bot:main`'
        required: false
        default: 'main'
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --image aaalexlit/faq-slack-bot:${{ github.event.inputs.docker_tag }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}